# Generated by Django 4.2.16 on 2026-05-28 06:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='명소명')),
                ('description', models.TextField(verbose_name='설명')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('view_azimuth', models.FloatField(help_text='이 명소에서 노을을 바라보는 방향 (0=북, 90=동, 180=남, 270=서)', verbose_name='조망 방위각')),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='spots/examples/', verbose_name='대표 사진')),
                ('tags', models.CharField(blank=True, help_text='쉼표로 구분 (예: 해변,사진맛집,주차가능)', max_length=200, verbose_name='태그')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '노을 명소',
                'verbose_name_plural': '노을 명소 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpotPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spots/photos/', verbose_name='사진')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='사진 설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spots.spot', verbose_name='명소')),
            ],
            options={
                'verbose_name': '명소 사진',
                'verbose_name_plural': '명소 사진 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='후기 내용')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('visit_date', models.DateField(verbose_name='방문 날짜')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/images/', verbose_name='사진')),
                ('video', models.FileField(blank=True, null=True, upload_to='reviews/videos/', verbose_name='영상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='spots.spot', verbose_name='명소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '후기',
                'verbose_name_plural': '후기 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
