# Generated by Django 5.2.14 on 2026-05-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='accessibility',
            field=models.IntegerField(choices=[(1, '어려움 — 등산·험로 필요'), (2, '보통 — 10분 이상 도보'), (3, '좋음 — 5분 이내 도보·주차 가능'), (4, '매우 좋음 — 차에서 바로 접근')], default=3, help_text='일반인 기준 접근 난이도', verbose_name='접근 용이성'),
        ),
        migrations.AddField(
            model_name='spot',
            name='cover_url',
            field=models.URLField(blank=True, default='', help_text='공식 관광 사이트 등 외부 이미지 URL', verbose_name='대표 사진 URL'),
        ),
        migrations.AddField(
            model_name='spot',
            name='is_official',
            field=models.BooleanField(default=False, help_text='제주도 지정 관광지·도립공원 등 공식 명소 여부', verbose_name='공식 관광지'),
        ),
        migrations.AddField(
            model_name='spot',
            name='view_openness',
            field=models.IntegerField(choices=[(1, '부분 차단 — 건물·나무 등 장애물 있음'), (2, '양호 — 시야 대부분 확보'), (3, '완전 개방 — 바다·들판 무장애 파노라마')], default=2, help_text='일몰 방향의 시야 확보 수준', verbose_name='시야 개방도'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='example_image',
            field=models.ImageField(blank=True, null=True, upload_to='spots/examples/', verbose_name='직접 업로드 사진'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='tags',
            field=models.CharField(blank=True, help_text='쉼표로 구분 (예: 해변,오름,주차가능)', max_length=200, verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='view_azimuth',
            field=models.FloatField(help_text='노을을 바라보는 방향 (0=북 · 90=동 · 180=남 · 270=서)', verbose_name='조망 방위각'),
        ),
    ]
