# Generated by Django 5.2.14 on 2026-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_spot_accessibility_spot_cover_url_spot_is_official_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='사진 URL'),
        ),
    ]
